# Generated by Django 5.2.4 on 2025-07-14 21:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0002_alter_student_group"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="student",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.DO_NOTHING, to="students.student"
            ),
        ),
    ]
