# Generated by Django 5.2.4 on 2025-07-14 21:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0003_alter_payment_student"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="student",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="students.student"
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="students.group"
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="offer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="students.offer"
            ),
        ),
    ]
